### PR TITLE
Add method to add multiple variables to the process's environment

### PR DESCRIPTION
**Pull request by systemhalted**
1. The user can now pass a Map of environment variables using method `withVars`
2. Added the test
3. Update README

### CODE REVIEW

**Comment by systemhalted** [comment]
This caters to part 2 of https://github.com/fleipold/jproc/issues/28

**Review by fleipold — APPROVED** [review]
@systemhalted thank you very much for your contribution (including the documentation for the README.md :) ). I'll just pull this now and start the release process (which isn't as automated as it should be, perhaps one day I'll use mill to script the build, it is actually really good at getting stuff all the way into maven central).

**Comment by systemhalted** [comment]
Thank you for approving and merging the request.

**Comment by systemhalted** [comment]
I have never used mill. You are the first person to mention it. I will try it out soon.

**Pull request merged**
